In [29]:
import numpy as np

In [30]:
np.array([1, 2])

array([1, 2])

In [31]:
np.dtype(np.int32)

dtype('int32')

In [32]:
np.dtype('<i4')

dtype('int32')

In [33]:
np.dtype('i4')

dtype('int32')

In [34]:
a = np.arange(24)

In [35]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [36]:
a.ndim

1

In [37]:
b = a.reshape(2, 4, 3)

In [38]:
b

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [39]:
c = a.reshape(2, 3, 4)

In [40]:
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [41]:
np.__version__

'1.20.3'