In [21]:
import numpy as np

In [22]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
x2 = np.arange(15).reshape(3, 5) # reshape 转换为 3行5列的矩阵
x2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

## 基本属性

In [24]:
x.ndim # 返回几维数组

1

In [25]:
x2.ndim

2

In [26]:
x.shape # 返回矩阵，几行几列

(10,)

In [27]:
x2.shape

(3, 5)

In [28]:
x.size # 返回元素个数

10

In [29]:
x2.size

15

## numpy.array 的数据访问

In [30]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
x[5]

5

In [32]:
x[-1] # 最后一个元素

9

In [33]:
x2[2][2]

12

In [35]:
x2[(2,2)] # np 方式的获取多维下标数据（推荐）

12

In [36]:
x[3:5] # 切片 返回3开始到5的元素

array([3, 4])

In [37]:
x[:5]

array([0, 1, 2, 3, 4])

In [38]:
x[5:]

array([5, 6, 7, 8, 9])

In [39]:
x[::2] # 获取步长为2的数据

array([0, 2, 4, 6, 8])

In [40]:
x[::-1] # 相当于倒序

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [42]:
x2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [43]:
x2[:2, :3] # 多维数组，返回前两行，前三列

array([[0, 1, 2],
       [5, 6, 7]])

In [44]:
x2[:2][:3] # 返回前两行后,在返回前三行

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [45]:
x2[:2][:1]

array([[0, 1, 2, 3, 4]])