## Python - List 特点

In [1]:
L = [i for i in range(10)]

In [2]:
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
L[5]

5

In [4]:
L[5] = "111"

In [5]:
L

[0, 1, 2, 3, 4, '111', 6, 7, 8, 9]

In [6]:
import array

In [7]:
arr = array.array('i', [i for i in range(100)])

In [8]:
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [9]:
arr[5]

5

In [10]:
arr[6] = "123123" # array 的强制数据类型

TypeError: an integer is required (got type str)

In [12]:
arr[6] = 1111

In [13]:
arr

array('i', [0, 1, 2, 3, 4, 5, 1111, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

## numpy.array

In [14]:
import numpy as np

In [15]:
narr = np.array([i for i in range(10)])

In [16]:
narr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
narr[8]

8

In [18]:
narr[5] = 1000

In [19]:
narr

array([   0,    1,    2,    3,    4, 1000,    6,    7,    8,    9])

In [20]:
narr[10] = "123123" # 强数据类型

IndexError: index 10 is out of bounds for axis 0 with size 10

In [21]:
narr.dtype  # 获取数据类型

dtype('int64')

In [22]:
narr[8] = 50.1 # 浮点型（注意数据转换）

In [23]:
narr # 将浮点数转换为整形

array([   0,    1,    2,    3,    4, 1000,    6,    7,   50,    9])

**一般浮点型的会建议如下编写：**

In [24]:
narr1 = np.array([1, 2, 3.]) # 注意小数点

In [25]:
narr1

array([1., 2., 3.])

In [26]:
narr1.dtype

dtype('float64')

## 其他创建 numpy.array 的方法

In [27]:
np.zeros(10) # 创建N个0

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [28]:
np.zeros(10).dtype

dtype('float64')

In [29]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [30]:
np.zeros(10, dtype=float)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [31]:
np.zeros((3, 5)) # 三行五列数据

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [32]:
np.zeros(shape=(3, 5), dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [33]:
np.ones((3, 5)) # 创建N个1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [34]:
np.full((3, 4), 444) # 创建矩阵数量的值

array([[444, 444, 444, 444],
       [444, 444, 444, 444],
       [444, 444, 444, 444]])

In [35]:
np.full(shape=(3, 4), fill_value=100)

array([[100, 100, 100, 100],
       [100, 100, 100, 100],
       [100, 100, 100, 100]])

In [36]:
np.full(10, 100) # 创建10个100

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [37]:
np.full(10, 100.)

array([100., 100., 100., 100., 100., 100., 100., 100., 100., 100.])

In [38]:
np.full(fill_value=100, shape=20) # 顺序更换

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100])

### arrange

In [39]:
[i for i in range(10)] # 创建0到10的数据

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [40]:
[i for i in range(3, 41, 2)] # 创建起始3，结尾41（不含），步进为2的数据

[3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39]

In [41]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
np.arange(4, 30, 3)

array([ 4,  7, 10, 13, 16, 19, 22, 25, 28])

In [43]:
[i for i in range(3, 41, 2.0)] # 不支持浮点的补进

TypeError: 'float' object cannot be interpreted as an integer

In [44]:
[i for i in range(3., 41., 2.0)] # 不支持浮点的补进

TypeError: 'float' object cannot be interpreted as an integer

In [60]:
np.arange(3, 41, 2.1) # np 支持

array([ 3. ,  5.1,  7.2,  9.3, 11.4, 13.5, 15.6, 17.7, 19.8, 21.9, 24. ,
       26.1, 28.2, 30.3, 32.4, 34.5, 36.6, 38.7, 40.8])

In [61]:
np.arange(3.5, 41.6, 2.1)

array([ 3.5,  5.6,  7.7,  9.8, 11.9, 14. , 16.1, 18.2, 20.3, 22.4, 24.5,
       26.6, 28.7, 30.8, 32.9, 35. , 37.1, 39.2, 41.3])

### linspace

In [62]:
np.linspace(0, 20, 10)  # 将起点与终点20，取10个数据（等长）

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [63]:
np.linspace(0, 20, 11) # 包含20

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [64]:
np.linspace(0, 20, 11, dtype=int)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

### random

In [65]:
np.random.randint(0, 10) # 0~10的随机数（不含10）

0

In [66]:
np.random.randint(0, 10, 3)  # 0~10范围生成3个（不含10）
np.random.randint(4, 10, size=10) 

array([8, 4, 6, 9, 5, 7, 5, 6, 9, 4])

In [67]:
np.random.randint(0, 1, 10) # 10个0，因为1不含

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [68]:
np.random.randint(4, 10, size=10) 

array([5, 5, 9, 4, 6, 7, 9, 4, 8, 6])

In [69]:
np.random.randint(4, 10, size=(3, 10)) # 生成矩阵，3行，10列

array([[4, 7, 7, 5, 6, 9, 5, 4, 6, 5],
       [4, 5, 5, 4, 5, 6, 8, 6, 5, 5],
       [8, 4, 4, 9, 5, 4, 8, 8, 4, 6]])

In [70]:
np.random.seed() # 指定随机种子

np.random.seed(10)
print(np.random.randint(4, 10, size=10))
np.random.seed(10)
print(np.random.randint(4, 10, size=10))

[5 9 8 4 5 7 8 5 9 4]
[5 9 8 4 5 7 8 5 9 4]


In [71]:
np.random.random()  # 0~1之间的随机浮点数

0.02517172841774562

In [72]:
a = np.random.random(10) #生成10个随机数
b = np.random.random((3, 4)) #生成3行4列
a, b

(array([0.70920801, 0.26556613, 0.26360285, 0.15037787, 0.68381843,
        0.81660184, 0.33607158, 0.89081653, 0.19812181, 0.03061665]),
 array([[0.87761494, 0.72743551, 0.54088093, 0.13145815],
        [0.41366737, 0.77872881, 0.58390137, 0.18263144],
        [0.82608225, 0.10540183, 0.28357668, 0.06556327]]))

In [73]:
a = np.random.normal() # 符合正态分布的随机数
b = np.random.normal(10, 100) # 均值为10，方差为100的随机数
c = np.random.normal(10, 100, (3, 5)) # 矩阵
a, b, c

(0.6789311948270179,
 -181.35542132289785,
 array([[ -84.24580556, -164.5542979 ,  -92.09452668,   -6.20690262,
          -55.79708995],
        [  52.21130617,   72.40233379,   60.16400965,   94.14347266,
         -154.02499842],
        [ 115.80051586,    0.82155575,  -62.40345933,  -30.04603572,
           54.53245845]]))

In [78]:
# 通过问号，查看参数文档
np.random.randint?

Docstring:
randint(low, high=None, size=None, dtype=int)

Return random integers from `low` (inclusive) to `high` (exclusive).

Return random integers from the "discrete uniform" distribution of
the specified dtype in the "half-open" interval [`low`, `high`). If
`high` is None (the default), then results are from [0, `low`).

.. note::
    New code should use the ``integers`` method of a ``default_rng()``
    instance instead; please see the :ref:`random-quick-start`.

Parameters
----------
low : int or array-like of ints
    Lowest (signed) integers to be drawn from the distribution (unless
    ``high=None``, in which case this parameter is one above the
    *highest* such integer).
high : int or array-like of ints, optional
    If provided, one above the largest (signed) integer to be drawn
    from the distribution (see above for behavior if ``high=None``).
    If array-like, must contain integer values
size : int or tuple of ints, optional
    Output shape.  If the given shape is, 

In [79]:
np.random?

Type:        module
String form: <module 'numpy.random' from '/usr/local/lib/python3.9/site-packages/numpy/random/__init__.py'>
File:        /usr/local/lib/python3.9/site-packages/numpy/random/__init__.py
Docstring:  
Random Number Generation

Use ``default_rng()`` to create a `Generator` and call its methods.

=============== =========================================================
Generator
--------------- ---------------------------------------------------------
Generator       Class implementing all of the random number distributions
default_rng     Default constructor for ``Generator``
=============== =========================================================

============================================= ===
BitGenerator Streams that work with Generator
--------------------------------------------- ---
MT19937
PCG64
Philox
SFC64
============================================= ===

============================================= ===
Getting entropy to initialize a BitGenerator
-------

In [80]:
# 查看帮助文档
help(np.random)

 out in the distribution does the t
        statistic appear?
        
        >>> np.sum(s<t) / float(len(s))
        0.0090699999999999999  #random
        
        So the p-value is about 0.009, which says the null hypothesis has a
        probability of about 99% of being true.
    
    triangular(...) method of numpy.random.mtrand.RandomState instance
        triangular(left, mode, right, size=None)
        
        Draw samples from the triangular distribution over the
        interval ``[left, right]``.
        
        The triangular distribution is a continuous probability
        distribution with lower limit left, peak at mode, and upper
        limit right. Unlike the other distributions, these parameters
        directly define the shape of the pdf.
        
        .. note::
            New code should use the ``triangular`` method of a ``default_rng()``
            instance instead; please see the :ref:`random-quick-start`.
        
        Parameters
        ----------
