## Python - List 特点

In [1]:
L = [i for i in range(10)]

In [3]:
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
L[5]

5

In [5]:
L[5] = "111"

In [6]:
L

[0, 1, 2, 3, 4, '111', 6, 7, 8, 9]

In [7]:
import array

In [8]:
arr = array.array('i', [i for i in range(100)])

In [9]:
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [10]:
arr[5]

5

In [11]:
arr[6] = "123123" # array 的强制数据类型

TypeError: an integer is required (got type str)

In [12]:
arr[6] = 1111

In [13]:
arr

array('i', [0, 1, 2, 3, 4, 5, 1111, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

## numpy.array

In [1]:
import numpy as np

In [4]:
narr = np.array([i for i in range(10)])

In [5]:
narr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
narr[8]

8

In [7]:
narr[5] = 1000

In [8]:
narr

array([   0,    1,    2,    3,    4, 1000,    6,    7,    8,    9])

In [9]:
narr[10] = "123123" # 强数据类型

IndexError: index 10 is out of bounds for axis 0 with size 10

In [12]:
narr.dtype  # 获取数据类型

dtype('int32')

In [13]:
narr[8] = 50.1 # 浮点型（注意数据转换）

In [14]:
narr # 将浮点数转换为整形

array([   0,    1,    2,    3,    4, 1000,    6,    7,   50,    9])

**一般浮点型的会建议如下编写：**

In [17]:
narr1 = np.array([1, 2, 3.]) # 注意小数点

In [18]:
narr1

array([1., 2., 3.])

In [19]:
narr1.dtype

dtype('float64')

## 其他创建 numpy.array 的方法

In [20]:
np.zeros(10) # 创建N个0

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [21]:
np.zeros(10).dtype

dtype('float64')

In [22]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [23]:
np.zeros(10, dtype=float)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [24]:
np.zeros((3, 5)) # 三行五列数据

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [25]:
np.zeros(shape=(3, 5), dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [26]:
np.ones((3, 5)) # 创建N个1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [30]:
np.full((3, 4), 444) # 创建矩阵数量的值

array([[444, 444, 444, 444],
       [444, 444, 444, 444],
       [444, 444, 444, 444]])

In [31]:
np.full(shape=(3, 4), fill_value=100)

array([[100, 100, 100, 100],
       [100, 100, 100, 100],
       [100, 100, 100, 100]])

In [33]:
np.full(10, 100) # 创建10个100

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [34]:
np.full(10, 100.)

array([100., 100., 100., 100., 100., 100., 100., 100., 100., 100.])

In [36]:
np.full(fill_value=100, shape=20) # 顺序更换

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100])

### arrange

In [44]:
[i for i in range(10)] # 创建0到10的数据

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [45]:
[i for i in range(3, 41, 2)] # 创建起始3，结尾41（不含），步进为2的数据

[3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39]

In [46]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
np.arange(4, 30, 3)

array([ 4,  7, 10, 13, 16, 19, 22, 25, 28])

In [48]:
[i for i in range(3, 41, 2.0)] # 不支持浮点的补进

TypeError: 'float' object cannot be interpreted as an integer

In [49]:
[i for i in range(3., 41., 2.0)] # 不支持浮点的补进

TypeError: 'float' object cannot be interpreted as an integer

In [50]:
np.arange(3, 41, 2.1) # np 支持

array([ 3. ,  5.1,  7.2,  9.3, 11.4, 13.5, 15.6, 17.7, 19.8, 21.9, 24. ,
       26.1, 28.2, 30.3, 32.4, 34.5, 36.6, 38.7, 40.8])

In [51]:
np.arange(3.5, 41.6, 2.1)

array([ 3.5,  5.6,  7.7,  9.8, 11.9, 14. , 16.1, 18.2, 20.3, 22.4, 24.5,
       26.6, 28.7, 30.8, 32.9, 35. , 37.1, 39.2, 41.3])

### linspace

In [52]:
np.linspace(0, 20, 10)  # 将起点与终点20，取10个数据（等长）

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [53]:
np.linspace(0, 20, 11) # 包含20

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [54]:
np.linspace(0, 20, 11, dtype=int)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

### random

In [79]:
np.random.randint(0, 10) # 0~10的随机数（不含10）

2

In [85]:
np.random.randint(0, 10, 3)  # 0~10范围生成3个（不含10）
np.random.randint(4, 10, size=10) 

array([8, 8, 7, 7, 7, 4, 8, 7, 9, 8])

In [84]:
np.random.randint(0, 1, 10) # 10个0，因为1不含

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
np.random.randint(4, 10, size=10) 

In [86]:
np.random.randint(4, 10, size=(3, 10)) # 生成矩阵，3行，10列

array([[5, 5, 9, 5, 4, 6, 4, 4, 7, 6],
       [9, 8, 9, 6, 9, 7, 4, 7, 6, 5],
       [7, 6, 5, 5, 9, 4, 6, 7, 7, 4]])

In [89]:
np.random.seed() # 指定随机种子

np.random.seed(10)
print(np.random.randint(4, 10, size=10))
np.random.seed(10)
print(np.random.randint(4, 10, size=10))

[5 9 8 4 5 7 8 5 9 4]
[5 9 8 4 5 7 8 5 9 4]


In [91]:
np.random.random()  # 0~1之间的随机浮点数

0.709208009843012

In [95]:
a = np.random.random(10) #生成10个随机数
b = np.random.random((3, 4)) #生成3行4列
a, b

(array([0.07979268, 0.2350386 , 0.65996495, 0.21495319, 0.20304662,
        0.38286511, 0.2248728 , 0.1146488 , 0.58301705, 0.23264106]),
 array([[5.56518188e-01, 5.23810885e-01, 3.50958224e-01, 7.05331613e-01],
        [8.20703741e-01, 1.34563003e-01, 6.04726160e-01, 2.83148276e-01],
        [5.06407820e-01, 3.84604283e-02, 3.32444096e-01, 2.72531491e-04]]))

In [104]:
a = np.random.normal() # 符合正态分布的随机数
b = np.random.normal(10, 100) # 均值为10，方差为100的随机数
c = np.random.normal(10, 100, (3, 5)) # 矩阵
a, b, c

(-0.7958489517182998,
 -105.80872182083152,
 array([[  67.42180744,  103.26223245,   19.09150182, -137.39951697,
           21.05580581],
        [  35.36799506,   36.48817876,   82.4772178 ,  -43.53548789,
           -9.0604927 ],
        [ -37.06766077,  -26.2615081 ,  -68.85675633,  135.6569501 ,
         -110.6461611 ]]))

In [105]:
np.random.randint?  # 通过问号，查看参数文档

Docstring:
randint(low, high=None, size=None, dtype=int)

Return random integers from `low` (inclusive) to `high` (exclusive).

Return random integers from the "discrete uniform" distribution of
the specified dtype in the "half-open" interval [`low`, `high`). If
`high` is None (the default), then results are from [0, `low`).

.. note::
    New code should use the ``integers`` method of a ``default_rng()``
    instance instead; please see the :ref:`random-quick-start`.

Parameters
----------
low : int or array-like of ints
    Lowest (signed) integers to be drawn from the distribution (unless
    ``high=None``, in which case this parameter is one above the
    *highest* such integer).
high : int or array-like of ints, optional
    If provided, one above the largest (signed) integer to be drawn
    from the distribution (see above for behavior if ``high=None``).
    If array-like, must contain integer values
size : int or tuple of ints, optional
    Output shape.  If the given shape is, 